import { NgModule } from '@angular/core';
import {
  TextAlignJustify,
  ArrowRight,
  Ellipsis,
  EllipsisVertical,
  Loader,
  LogIn,
  LucideAngularModule,
  Moon,
  Search,
  SquarePen,
  Sun,
  UserRound,
  KeyRound,
  CircleAlert,
  EyeClosed,
  Eye,
  ArrowUp,
  ChevronsLeft,
  Settings,
  CircleUserRound,
  ChevronsUpDown,
  Copy,
  Pencil,
  ThumbsDown,
  ThumbsUp,
  RefreshCw,
} from 'lucide-angular';

@NgModule({
  declarations: [],
  imports: [
    LucideAngularModule.pick({
      Search,
      SquarePen,
      TextAlignJustify,
      EllipsisVertical,
      Sun,
      Moon,
      Ellipsis,
      ArrowRight,
      LogIn,
      Loader,
      UserRound,
      KeyRound,
      CircleAlert,
      EyeClosed,
      Eye,
      ArrowUp,
      ChevronsLeft,
      Settings,
      CircleUserRound,
      ChevronsUpDown,
      Copy,
      Pencil,
      ThumbsDown,
      ThumbsUp,
      RefreshCw,
    }),
  ],
  exports: [LucideAngularModule],
})
export class LucideIconsModule {}
